QMainWindow {
    background: black;
    color: white;
}

QPushButton {
    color: #00ff00;
    background: #000000;
    border: 1px solid #004000;
    border-radius: 3px;
    padding: 5px;
}

QPushButton:hover {
    background: #002200;
    border: 1px solid #008000;
}

QPushButton:pressed {
    background: #004400;
    border: 1px solid #00aa00;
}

QMessageBox {
    background: #002200;
    color: #008800;
    border: #00ff00;
}

QMessageBox QLabel {
    color: #008800;
}

QCheckBox {
    color: #ffffff;
}

QCheckBox::indicator {
    width: 16px;
    height: 16px;
}

QCheckBox::indicator:unchecked {
    background-image: url(":/theme/checkbox/unchecked3");
    background-position: center;
}

QCheckBox::indicator:checked {
    background-image: url(":/theme/checkbox/checked3");
    background-position: center;
}

QRadioButton {
    color: #ffffff;
}

QRadioButton::indicator {
    width: 16px;
    height: 16px;
}

QRadioButton::indicator:unchecked {
    background-image: url(":/theme/radio/hacker/unchecked");
    background-position: center;
}

QRadioButton::indicator:checked {
    background-image: url(":/theme/radio/hacker/checked");
    background-position: center;
}

QRadioButton::indicator:unchecked:hover {
    background-image: url(":/theme/radio/hacker/unchecked-hover");
    background-position: center;
}

QRadioButton::indicator:checked:hover {
    background-image: url(":/theme/radio/hacker/checked-hover");
    background-position: center;
}

QCheckBox:disabled {
    color: gray;
}

QLineEdit {
    background: #000000;
    color: #ffffff;
    border: 1px solid #004400;
    border-radius: 5px;
    padding: 1px;
}

QLineEdit:focus {
    color: #ffffff;
    border: 1px solid #00ff00;
}

QLineEdit:disabled {
    background: #000000;
    color: #888888;
    border: 1px solid #002200;
}

QSpinBox {
    padding-right: 15px;
    padding-left: 2px;
    color: #ffffff;
    border: 1px solid #008000;
    background: #000000;
    border-radius: 5px;
}

QSpinBox:focus {
    border: 1px solid #00ff00;
}

QSpinBox::up-button {
    subcontrol-origin: border;
    subcontrol-position: top right;
    width: 15px;
    border: 1px solid #008000;
    background: #000000;
    height: 14px;
}

QSpinBox::up-button:hover {
    border: 1px solid #00ff00;
    background: #000000;
}

QSpinBox::up-button:pressed {
    border: 1px solid #55ff55;
    background: #000000;
}

QSpinBox::up-arrow {
    image: url(":/theme/spin/up2");
    width: 7px;
    height: 7px;
}

QSpinBox::up-arrow:disabled,
QSpinBox::up-arrow:off {
    /* off state when value is max */
    image: url(":/theme/spin/up-off");
}

QSpinBox::down-button {
    subcontrol-origin: border;
    subcontrol-position: bottom right;
    width: 15px;
    border: 1px solid #008000;
    background: #000000;
    height: 14px;
}

QSpinBox::down-button:hover {
    border: 1px solid #00ff00;
    background: #000000;
}

QSpinBox::down-button:pressed {
    border: 1px solid #55ff55;
    background: #000000;
}

QSpinBox::down-arrow {
    image: url(":/theme/spin/down2");
    width: 7px;
    height: 7px;
}

QSpinBox::down-arrow:disabled,
QSpinBox::down-arrow:off {
    /* off state when value in min */
    image: url(":/theme/spin/down-off");
}

QLabel {
    color: #0000ff;
    background: none;
    border: none;
}

QLine {
    background: #222222;
    border: 1px solid #444444;
    border-radius: 1px;
}

QListWidget {
    color: #ffffff;
    background: #000000;
    border: 2px solid #008800;
    border-radius: 5px;
}

QListWidget:focus {
    color: #ffffff;
    background: #000000;
    border: 2px solid #00ff00;
}

QListWidget::item {
    background: none;
    color: #ffffff;
    border-radius: 5px;
}

QListWidget::item:selected {
    background: #008800;
    color: #ffffff;
    border-radius: 5px;
}

QTextEdit {
    color: #00ff00;
    background: #000000;
    border: 2px solid #00ff00;
    border-radius: 5px;
}


/*
QTextEdit QScrollBar:vertical {
    background: #440000;
    border: 2px solid #808080;
}

QTextEdit QScrollBar::up-arrow:vertical {
    background: url(":/theme/spin/up2");
}

QTextEdit QScrollBar::down-arrow:vertical {
    background: url(":/theme/spin/down2");
}
*/